name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy-edge-fns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

    - name: Setup Deno
  uses: denoland/setup-deno@v1
  with:
    deno-version: 1.37.2


      - name: Install Supabase CLI
        run: |
          curl -sSL https://github.com/supabase/cli/releases/download/v1.0.0/supabase_1.0.0_linux_amd64.tar.gz -o supabase-cli.tar.gz
          tar -xvzf supabase-cli.tar.gz
          sudo mv supabase /usr/local/bin/

      - name: Deploy email-processor function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          supabase functions deploy email-processor --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Deploy generate-response function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          supabase functions deploy generate-response --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
