name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy-edge-fns:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Deno
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Setup Supabase CLI
      - name: Setup Supabase CLI
        run: |
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -  # Installs Node.js 18.x
          sudo apt-get install -y nodejs  # Installs Node.js
          npm install -g supabase  # Installs the Supabase CLI

      # Deploy email-processor function
      - name: Deploy email-processor function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          supabase functions deploy email-processor --project-ref $SUPABASE_PROJECT_ID

      # Deploy generate-response function
      - name: Deploy generate-response function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          supabase functions deploy generate-response --project-ref $SUPABASE_PROJECT_ID
