name: Auto-Responder
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
          python -m nltk.downloader vader_lexicon
      
      - name: Create and verify token.json
        run: |
          echo '${{ secrets.GMAIL_TOKEN_JSON }}' > token.json
          if [ -s token.json ]; then
            echo "Token created successfully"
            echo "First few chars of token: $(head -c 30 token.json)..."
          else
            echo "ERROR: Token creation failed"
            exit 1
          fi
      
      - name: Run Responder
        env:
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GITHUB_ACTIONS: "true"
        run: |
          echo "Starting responder..."
          python responder.py
