name: Auto-Responder
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
          python -m nltk.downloader vader_lexicon
      
      - name: Create and validate token
        run: |
          # Write token with proper newlines
          cat <<EOF > token.json
          ${{ secrets.GMAIL_TOKEN_JSON }}
          EOF
          
          # Strict validation
          if python -c "
import json, sys
try:
    with open('token.json') as f:
        data = json.load(f)
    assert 'token' in data or 'refresh_token' in data
    print('Token validation passed')
except Exception as e:
    print(f'Token validation failed: {str(e)}')
    sys.exit(1)
          "; then
            echo "Token is valid"
            echo "First 50 chars: $(head -c 50 token.json)"
          else
            echo "ERROR: Invalid token"
            exit 1
          fi
      
      - name: Run Responder
        env:
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GITHUB_ACTIONS: "true"
        run: |
          python responder.py
