name: Auto-Responder
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
          python -m nltk.downloader vader_lexicon
      
      - name: Create and validate token.json
        run: |
          # Create token file without jq validation
          echo '${{ secrets.GMAIL_TOKEN_JSON }}' > token.json
          
          # Python-based JSON validation
          if python -c "import json, sys; json.load(open('token.json')); print('Token is valid JSON')"; then
            echo "Token created successfully"
            echo "Token size: $(wc -c < token.json) bytes"
          else
            echo "ERROR: Invalid token.json"
            exit 1
          fi
      
      - name: Run Responder
        env:
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GITHUB_ACTIONS: "true"
        run: |
          python responder.py
