jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
          python -m nltk.downloader vader_lexicon
      - name: Create token.json
        run: |
          echo '${{ secrets.GMAIL_TOKEN_JSON }}' > token.json
          # Verify token exists and contains data
          [ -s token.json ] && echo "Token created successfully" || echo "Token creation failed"
      - name: Run Responder
        env:
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GITHUB_ACTIONS: "true"
        run: python responder.py
